workflows:
    android-app: # workflow ID
        name: Android app # workflow name
        scripts:
            - ./gradlew assembleDebug
        artifacts:
            - build/outputs/**/**/*.apk
        publishing:
            email:
                recipients:
                    - johnson.hsu@artkernel.net
